services:
    mongodb:
        image: mongo:8.0
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME} # root пользователь
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD} # пароль для root
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE} # создается эта база данных
            - MONGO_INITDB_USER=${MONGO_INITDB_USER} # пользователь для базы данных
            - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD} # пароль для пользователя
        volumes:
            - mongodb_volume:/data/db

volumes:
    mongodb_volume: 